# -*- coding: utf-8 -*-
"""transformer generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EETSdOCH7ZcbSU9XbWD5xoIYsDJ2mqoy
"""

from transformers import pipeline

# Load text generation model (GEN-AI)
generator = pipeline(
    "text-generation",
    model="gpt2"
)

# Input prompt
prompt = "Artificial Intelligence in finance will"

# Generate text
result = generator(prompt,max_length=50,num_return_sequences=1)

print("AI Generated text:")
print(result[0]['generated_text'])